name: Weekly Node.js Script

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 (midnight)

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Needed for git commit
        
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Run Node.js script
      run: |
        node script.js
      env:
        # Any environment variables needed by your script
        MY_ENV_VAR: ${{ secrets.MY_ENV_VAR }}
        
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update from weekly script" || echo "No changes to commit"
        git push origin HEAD
